os:
  - linux
  - osx

language: cpp

sudo: false
dist: trusty
osx_image: xcode7

before_install:

install:

script:
  echo "Building the library...";
  mkdir build && cd build;
  cmake .. -DBUILD_SHARED_LIBS=true;
  cmake --build .;
